// lib/firebase_options.dart
// This file is auto-generated by 'flutterfire configure' after linking a
// Firebase project. Run `flutterfire configure` to generate the real file.
// See README "Firebase Setup" section for instructions.

class DefaultFirebaseOptions {
  static const String? webApiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
  static const String? androidApiKey = String.fromEnvironment('FIREBASE_ANDROID_API_KEY');
  static const String? iosApiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');

  static const String? projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
  static const String? messagingSenderId =
      String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID');
  static const String? appId = String.fromEnvironment('FIREBASE_APP_ID');
}
